### ISSUE TITLE
cmake error 

### ISSUE THREAD

**Issue by gitshitou** [shrit/MagicFlock#1]
hello,  there is an error,when  build the project.

CMake Error at src/MagicFlock/CMakeLists.txt:81 (install):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "MagicFlock".

how can I solve that?

thank you

**Comment by shrit** [comment]
Hi,

Would you share the steps that you have followed, so I can reproduce the error?
Many thanks

**Comment by gitshitou** [comment]
Follow the steps as below

git clone https://github.com/shrit/MagicFlock.git
cd MagicFlock
git submodule update --init --recursive
mkdir build
cmake . ./
...
when  execute cmake , An error will occur。

-- cotire 1.8.1 loaded.
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   thread
--   system
--   filesystem
--   program_options
--   regex
--   iostreams
--   date_time
--   chrono
--   atomic
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.0.0") 
-- Boost version: 1.65.1
-- Looking for OGRE...
-- Found Ogre Ghadamon (1.9.0)
-- Found OGRE: optimized;/usr/lib/x86_64-linux-gnu/libOgreMain.so;debug;/usr/lib/x86_64-linux-gnu/libOgreMain.so
-- Looking for OGRE_Paging...
-- Found OGRE_Paging: optimized;/usr/lib/x86_64-linux-gnu/libOgrePaging.so;debug;/usr/lib/x86_64-linux-gnu/libOgrePaging.so
-- Looking for OGRE_Terrain...
-- Found OGRE_Terrain: optimized;/usr/lib/x86_64-linux-gnu/libOgreTerrain.so;debug;/usr/lib/x86_64-linux-gnu/libOgreTerrain.so
-- Looking for OGRE_Property...
-- Found OGRE_Property: optimized;/usr/lib/x86_64-linux-gnu/libOgreProperty.so;debug;/usr/lib/x86_64-linux-gnu/libOgreProperty.so
-- Looking for OGRE_RTShaderSystem...
-- Found OGRE_RTShaderSystem: optimized;/usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so;debug;/usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so
-- Looking for OGRE_Volume...
-- Found OGRE_Volume: optimized;/usr/lib/x86_64-linux-gnu/libOgreVolume.so;debug;/usr/lib/x86_64-linux-gnu/libOgreVolume.so
-- Looking for OGRE_Overlay...
-- Found OGRE_Overlay: optimized;/usr/lib/x86_64-linux-gnu/libOgreOverlay.so;debug;/usr/lib/x86_64-linux-gnu/libOgreOverlay.so
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread;-lpthread (found suitable version "3.0.0", minimum required is "2.3.0") 
-- Config-file not installed for ZeroMQ -- checking for pkg-config
-- Checking for module 'libzmq >= 4'
--   Found libzmq , version 4.2.5
-- Checking for module 'uuid'
--   Found uuid, version 2.31.1
-- Checking for module 'tinyxml2'
--   Found tinyxml2, version 6.0.0
-- Looking for dlfcn.h - found
-- Looking for libdl - found
-- FreeImage.pc not found, we will search for FreeImage_INCLUDE_DIRS and FreeImage_LIBRARIES
-- Checking for module 'gts'
--   Found gts, version 0.7.6
-- Checking for module 'libswscale'
--   Found libswscale, version 4.8.100
-- Checking for module 'libavdevice >= 56.4.100'
--   Found libavdevice , version 57.10.100
-- Checking for module 'libavformat'
--   Found libavformat, version 57.83.100
-- Checking for module 'libavcodec'
--   Found libavcodec, version 57.107.100
-- Checking for module 'libavutil'
--   Found libavutil, version 55.78.100
-- Checking for module 'jsoncpp'
--   Found jsoncpp, version 1.7.4
-- Checking for module 'yaml-0.1'
--   Found yaml-0.1, version 0.1.7
-- Checking for module 'libzip'
--   Found libzip, version 1.1.2
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   date_time
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread;-lpthread;-lpthread (found version "3.0.0") 
print cmake binary dir/home/shitou/MARL/MagicFlock
print cmake binary dir/home/shitou/MARL/MagicFlock/src/MagicFlock
CMake Error at src/MagicFlock/CMakeLists.txt:81 (install):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "MagicFlock".


-- Configuring incomplete, errors occurred!
See also "/home/shitou/MARL/MagicFlock/CMakeFiles/CMakeOutput.log".
See also "/home/shitou/MARL/MagicFlock/CMakeFiles/CMakeError.log".

**Comment by shrit** [comment]
It seems there is a minor bug with the library destination. I need to produce this error locally. I am currently away from my machine, I will try to reproduce this error and I let you know tomorrow.

**Comment by gitshitou** [comment]
many thanks



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | Omar ***@***.***> |
| 日期 | 2021年12月22日 23:20 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [shrit/MagicFlock] cmake error (Issue #1) |

It seems there is a minor bug with the library destination. I need to produce this error locally. I am currently away from may machine, I will try to reproduce this error and I let you know tomorrow.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shrit** [comment]
@gitshitou I have resolved the issue, it was related to a small typo.
I have pushed the modification, please pull the last modifications and clean the build directory and let me know if this resolves your issue.

**Comment by gitshitou** [comment]
> @gitshitou I have resolved the issue, it was related to a small typo. I have pushed the modification, please pull the last modifications and clean the build directory and let me know if this resolves your issue.

The problem has been resolved, thanks

**Comment by shrit** [comment]
Perfect, I am closing this issue, do not hesitate in re-opening this issue or a new one if you have any difficulties.
